/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Images;

import View.CustmerManage11;
import View.ItemManage;
import View.Orderform;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author dpman
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    Color DefaultColor,ClickedColor,HoveredColor;
    public DashBoard() {
        initComponents();
        DefaultColor= new Color(255, 255, 255);
        ClickedColor= new Color(255, 160, 122);
        HoveredColor= new Color(255, 191, 0);
        
        Customer.setBackground(DefaultColor);
        Item.setBackground(DefaultColor);
        Order.setBackground(DefaultColor);

        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Item = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Order = new javax.swing.JLabel();
        Customer = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Free_Sample_By_Wix.jpg"))); // NOI18N

        Item.setBackground(new java.awt.Color(255, 255, 255));
        Item.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Item.setForeground(new java.awt.Color(255, 51, 0));
        Item.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/inventory.png"))); // NOI18N
        Item.setText("    Item");
        Item.setToolTipText("");
        Item.setOpaque(true);
        Item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ItemMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ItemMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("      Dashboard");
        jLabel6.setToolTipText("");

        Order.setBackground(new java.awt.Color(255, 255, 255));
        Order.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Order.setForeground(new java.awt.Color(255, 51, 0));
        Order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/cash-flow.png"))); // NOI18N
        Order.setText("   Order");
        Order.setToolTipText("");
        Order.setOpaque(true);
        Order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OrderMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                OrderMousePressed(evt);
            }
        });

        Customer.setBackground(new java.awt.Color(255, 255, 255));
        Customer.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Customer.setForeground(new java.awt.Color(255, 51, 0));
        Customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/customer (4).png"))); // NOI18N
        Customer.setText("Customer");
        Customer.setToolTipText("");
        Customer.setOpaque(true);
        Customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CustomerMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CustomerMousePressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 102, 255));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("         Developed By D.P.B Manakal © 2020-2021 ");
        jLabel5.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Order, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addComponent(Item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addComponent(Customer, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(74, 74, 74)
                .addComponent(Customer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Item, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Order, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Smartwear Log.PNG"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 0, 610, 110));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Untitled-1.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 750, 360));

        jLabel3.setBackground(new java.awt.Color(204, 0, 102));
        jLabel3.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("     Wear Better Look Better...");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 600, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerMousePressed
        // TODO add your handling code here:
        Customer.setBackground(ClickedColor);
        Item.setBackground(DefaultColor);
        Order.setBackground(DefaultColor);

    }//GEN-LAST:event_CustomerMousePressed

    private void ItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemMousePressed
        // TODO add your handling code here:
        Customer.setBackground(DefaultColor);
        Item.setBackground(ClickedColor);
        Order.setBackground(DefaultColor);

    }//GEN-LAST:event_ItemMousePressed

    private void OrderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderMousePressed
        // TODO add your handling code here:
        Customer.setBackground(DefaultColor);
        Item.setBackground(DefaultColor);
        Order.setBackground(ClickedColor);

    }//GEN-LAST:event_OrderMousePressed

    private void CustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerMouseEntered
        // TODO add your handling code here:
        Customer.setBackground(HoveredColor);
        Item.setBackground(DefaultColor);
        Order.setBackground(DefaultColor);
    }//GEN-LAST:event_CustomerMouseEntered

    private void CustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerMouseClicked
        // TODO add your handling code here:
        new CustmerManage11().setVisible(true);
       
    }//GEN-LAST:event_CustomerMouseClicked

    private void ItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemMouseClicked
        // TODO add your handling code here:
        new ItemManage().setVisible(true);
    }//GEN-LAST:event_ItemMouseClicked

    private void OrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderMouseClicked
        // TODO add your handling code here:
        new Orderform().setVisible(true);
    }//GEN-LAST:event_OrderMouseClicked

    private void CustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerMouseExited
        // TODO add your handling code here:
        Customer.setBackground(DefaultColor);
        Item.setBackground(DefaultColor);
        Order.setBackground(DefaultColor);
    }//GEN-LAST:event_CustomerMouseExited

    private void ItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemMouseEntered
        Customer.setBackground(DefaultColor);
        Item.setBackground(HoveredColor);
        Order.setBackground(DefaultColor);
    }//GEN-LAST:event_ItemMouseEntered

    private void ItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemMouseExited
        // TODO add your handling code here:
        Customer.setBackground(DefaultColor);
        Item.setBackground(DefaultColor);
        Order.setBackground(DefaultColor);
    }//GEN-LAST:event_ItemMouseExited

    private void OrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderMouseEntered
        // TODO add your handling code here:
        Customer.setBackground(DefaultColor);
        Item.setBackground(DefaultColor);
        Order.setBackground(HoveredColor);
    }//GEN-LAST:event_OrderMouseEntered

    private void OrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderMouseExited
    Customer.setBackground(DefaultColor);
        Item.setBackground(DefaultColor);
        Order.setBackground(DefaultColor);    }//GEN-LAST:event_OrderMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Customer;
    private javax.swing.JLabel Item;
    private javax.swing.JLabel Order;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
