/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ItemController;
import Controller.OrderController;
import DB.DBConnection;
import Model.ItemModel;
import Model.OrderDetailModel;
import Model.OrdersModel;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dpman
 */
public class Orderform extends javax.swing.JFrame {

    /**
     * Creates new form CustomerForm
     */
    public Orderform() {
        initComponents();
        loadcombo();
        loadcombo2();
        setResizable(false);
    }
    
       
        
        public void loadcombo(){
            
            try {
                OrderController controller = new OrderController();
                ArrayList <String> custIds = controller.loadCustomerId();
                for(String id:custIds){

                    CustomerId.addItem(id);
                    System.out.print(id);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Orderform.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Orderform.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        public void loadcombo2(){
        
            try {
                OrderController controller = new OrderController();
                ArrayList<String> ItemNames= controller.loadItemNames();
                        for(String name:ItemNames){

                            ItemName.addItem(name);
                        }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Orderform.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Orderform.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    public void clearTable(){
        jTable1.setModel(new DefaultTableModel(null,new String[]{"Order Id","Customer Id","ItemnName","Quantity","OrderDate"}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        OrderiD = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        ItemName = new javax.swing.JComboBox<>();
        btnPlaceOrder = new javax.swing.JButton();
        btnAddList = new javax.swing.JButton();
        txtQuantity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        OrderDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ItemCode = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CustomerId = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtUnitPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Description", "Quantity", "UnitPrice", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 620, 240));

        jLabel1.setFont(new java.awt.Font("Microsoft Himalaya", 0, 48)); // NOI18N
        jLabel1.setText("              Order Form");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 430, 84));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("OrderId:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 180, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Customer ID :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, 60));

        OrderiD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(OrderiD, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 230, 40));

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 150, 40));

        ItemName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemNameActionPerformed(evt);
            }
        });
        getContentPane().add(ItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 230, -1));

        btnPlaceOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPlaceOrder.setText("place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 150, 40));

        btnAddList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddList.setText("Add To List");
        btnAddList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddListActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddList, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 150, 40));

        txtQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 230, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("quantity :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 180, 60));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Order Date:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 180, 60));

        OrderDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(OrderDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 230, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Item Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 180, 60));

        ItemCode.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        getContentPane().add(ItemCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 230, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Item Code :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 180, 60));

        CustomerId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(CustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 230, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("UnitPrice :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 180, 60));

        txtUnitPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 230, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        
        OrderiD.setText("");
        OrderDate.setText("");
        ItemCode.setText("");
        txtQuantity.setText("");
        clearTable();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed

        String OrderId= OrderiD.getText();
        String CustId= CustomerId.getSelectedItem().toString();
        String orderDate=OrderDate.getText();
        ArrayList<OrderDetailModel> orderList= new ArrayList<>();
        
        DefaultTableModel dtm= (DefaultTableModel) jTable1.getModel();
        for(int i=0; i<dtm.getRowCount();i++){
            String itemCode= (String) jTable1.getValueAt(i, 0);
            Integer ordeQty= Integer.parseInt((String) jTable1.getValueAt(i, 2));
            Double UnitPrice= Double.parseDouble((String) jTable1.getValueAt(i, 3)); 
            OrderDetailModel item= new OrderDetailModel(OrderId,itemCode,ordeQty,UnitPrice);
            orderList.add(item);
        }
        
        OrdersModel order = new OrdersModel(OrderId,orderDate,CustId,orderList);
        boolean isAdded;
        try {
            isAdded = OrderController.placeOrder(order);
             if(isAdded){
                JOptionPane.showMessageDialog(this, "Added Success");
            }
        } 
        
        catch (ClassNotFoundException ex) {
            Logger.getLogger(Orderform.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Orderform.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnAddListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddListActionPerformed
        // TODO add your handling code here:
        String itemCode=ItemCode.getText();
        String Description=ItemName.getSelectedItem().toString();
        Integer quantity=Integer.parseInt(txtQuantity.getText());
        Double UnitPrice=Double.parseDouble(txtUnitPrice.getText());
        Double Total=UnitPrice*quantity;

        String[] data= {itemCode,Description,String.valueOf(quantity),String.valueOf(UnitPrice),String.valueOf(Total)};
        DefaultTableModel tblModel= (DefaultTableModel) jTable1.getModel();
        tblModel.addRow(data);
    }//GEN-LAST:event_btnAddListActionPerformed

    private void ItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemNameActionPerformed
        try {
            
            String itemName=ItemName.getSelectedItem().toString();
            PreparedStatement pst = DBConnection.getInstance().getConnection().prepareStatement("select * from item where item_description= ?");
            pst.setObject(1,itemName);
            ResultSet rst= pst.executeQuery();
            if(rst.next()){
                
                ItemCode.setText(String.valueOf(rst.getObject("item_code")));
                txtQuantity.setText(String.valueOf(rst.getObject("item_qtyOnHand")));
                txtUnitPrice.setText(String.valueOf(rst.getObject("item_unitPrice")));
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Orderform.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Orderform.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ItemNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orderform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orderform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orderform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orderform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orderform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CustomerId;
    private javax.swing.JLabel ItemCode;
    private javax.swing.JComboBox<String> ItemName;
    private javax.swing.JTextField OrderDate;
    private javax.swing.JTextField OrderiD;
    private javax.swing.JButton btnAddList;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables
}
